/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.BaseDatos;



/**
 *
 * @author Andrey
 */
public class PrincipalVentana extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalVentana
     */


    public static int numSeleccion=0;
  
    public PrincipalVentana() {
        
        initComponents();
       
        //seleccion();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbg_Seleccion = new javax.swing.ButtonGroup();
        jl_texto = new javax.swing.JLabel();
        jrb_Archivos = new javax.swing.JRadioButton();
        jrb_BaseDatos = new javax.swing.JRadioButton();
        jrb_Xml = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_texto.setText("Seleccione en que tipo de archivo desea guardar.");

        jbg_Seleccion.add(jrb_Archivos);
        jrb_Archivos.setText("Archivos");
        jrb_Archivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_ArchivosActionPerformed(evt);
            }
        });

        jbg_Seleccion.add(jrb_BaseDatos);
        jrb_BaseDatos.setText("Base De Datos");
        jrb_BaseDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_BaseDatosActionPerformed(evt);
            }
        });

        jbg_Seleccion.add(jrb_Xml);
        jrb_Xml.setText("XML");
        jrb_Xml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_XmlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrb_BaseDatos)
                            .addComponent(jrb_Archivos)
                            .addComponent(jrb_Xml)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jl_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_texto)
                .addGap(18, 18, 18)
                .addComponent(jrb_Archivos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrb_BaseDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrb_Xml)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrb_ArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_ArchivosActionPerformed
        
      numSeleccion=1;
      FRM_VentanaPrincipa VEN=new FRM_VentanaPrincipa();
      
     
     
//        
    }//GEN-LAST:event_jrb_ArchivosActionPerformed

    private void jrb_BaseDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_BaseDatosActionPerformed
        numSeleccion=2;
       FRM_VentanaPrincipa VEN=new FRM_VentanaPrincipa();
//      VEN.setVisible(true);
    }//GEN-LAST:event_jrb_BaseDatosActionPerformed

    private void jrb_XmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_XmlActionPerformed
         numSeleccion=3;
      FRM_VentanaPrincipa VEN=new FRM_VentanaPrincipa();
     
    }//GEN-LAST:event_jrb_XmlActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup jbg_Seleccion;
    private javax.swing.JLabel jl_texto;
    public javax.swing.JRadioButton jrb_Archivos;
    public javax.swing.JRadioButton jrb_BaseDatos;
    public javax.swing.JRadioButton jrb_Xml;
    // End of variables declaration//GEN-END:variables
}
